[package]
name = "ohttp-server"
version = "0.1.0"
authors = ["Martin Thomson <mt@lowentropy.net>"]
edition = "2018"

[dependencies]
# bytes = "1.0"
hex = "0.4"
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
warp = { version = "0.3", features = ["tls"] }

[dependencies.bhttp]
path= "../bhttp"
features = ["bhttp", "write-http"]

[dependencies.ohttp]
path= "../ohttp"
features = ["client"]
