[package]
name = "bhttp"
version = "0.2.3"
authors = ["Martin Thomson <mt@lowentropy.net>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Binary HTTP messages (draft-ietf-httpbis-binary-message)"
repository = "https://github.com/martinthomson/ohttp"

[features]
default = ["bhttp"]
bhttp = ["read-bhttp", "write-bhttp"]
http = ["read-http", "write-http"]
read-bhttp = []
write-bhttp = []
read-http = []
write-http = []

[dependencies]
url = "2"

[dev-dependencies]
hex = "0.4"
