[package]
name = "bhttp"
description = "Binary HTTP messages (draft-ietf-httpbis-binary-message)"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["bhttp"]
bhttp = ["read-bhttp", "write-bhttp"]
http = ["read-http", "write-http"]
read-bhttp = []
write-bhttp = []
read-http = ["url"]
write-http = []

[dependencies]
thiserror = "1"
url = {version = "2", optional = true}

[dev-dependencies]
hex = "0.4"
