[package]
name = "bhttp-convert"
version = "0.1.0"
authors = ["Martin Thomson <mt@lowentropy.net>"]
edition = "2018"

[dependencies]
structopt = "0.3.21"

[dependencies.bhttp]
path= "../bhttp"
features = ["bhttp", "http"]
