[package]
name = "ohttp"
version = "0.3.1"
authors = ["Martin Thomson <mt@lowentropy.net>"]
edition = "2021"
build = "build.rs"
license = "MIT OR Apache-2.0"
description = "Oblivious HTTP"
repository = "https://github.com/martinthomson/ohttp"

[features]
default = ["client", "server", "rust-hpke"]
client = []
server = []
nss = ["bindgen"]
rust-hpke = ["hpke/x25519", "rand", "aead", "aes-gcm", "chacha20poly1305", "hkdf", "sha2"]
gecko = ["mozbuild"]

[dependencies]
aead = {version = "0.4", optional = true, features = ["std"]}
aes-gcm = {version = "0.9", optional = true}
byteorder = "1.3"
chacha20poly1305 = {version = "0.8", optional = true}
hex = "0.4"
hkdf = {version = "0.11", optional = true}
hpke = {version = "0.10.0", optional = true, default-features = false, features = ["std"]}
lazy_static = "1.4"
log = {version = "0.4.0", default-features = false}
rand = {version = "0.8", optional = true}
sha2 = {version = "0.9", optional = true}
thiserror = "1"

[build-dependencies]
mozbuild = {version = "0.1", optional = true}
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"

[build-dependencies.bindgen]
version = "0.63"
default-features = false
optional = true
features = ["runtime"]

[dev-dependencies]
env_logger = {version = "0.9", default-features = false}
