[package]
name = "ohttp"
version = "0.1.0"
authors = ["Martin Thomson <mt@lowentropy.net>"]
edition = "2018"
build = "build.rs"

[features]
default = ["client", "server"]
client = []
server = []

[dependencies]
lazy_static = "1.4"
hex = "0.4"

[build-dependencies]
bindgen = {version = "0.56", default-features = false, features= ["runtime"]}
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
