name: CI
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -C link-arg=-fuse-ld=lld

jobs:
  build_and_test:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Build Prerequisites for NSS
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
            build-essential \
            ca-certificates \
            clang \
            coreutils \
            curl \
            git \
            gyp \
            libclang-dev \
            libssl-dev \
            lld \
            llvm \
            make \
            mercurial \
            ninja-build \
            pkg-config \
            ssh \
            zlib1g-dev \
            --no-install-recommends

      - name: Fetch NSS and NSPR
        run: |
          hg clone https://hg.mozilla.org/projects/nspr ./nspr
          git clone --depth 1 https://github.com/nss-dev/nss ./nss

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --tests
        env:
          NSS_DIR: ${{ github.workspace }}/nss

      - uses: actions-rs/cargo@v1
        name: Run Tests
        with:
          command: test
        env:
          NSS_DIR: ${{ github.workspace }}/nss
          LD_LIBRARY_PATH: ${{ github.workspace }}/dist/Debug/lib

      - uses: actions-rs/cargo@v1
        name: Check formatting
        if: ${{ success() || failure() }}
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        if: ${{ success() || failure() }}
        with:
          command: clippy
          args: --tests -- -D warnings
        env:
          NSS_DIR: ${{ github.workspace }}/nss
